[Interface]
# Key for VPS-Manager
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = AM0aGwCUxi6ByiWJyZS+l+eZOmsDRImQ7yiBeoglKEE=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SG-FREE#4
PublicKey = o+vYNpIDzf302SLUBLAG9zBf+M3nBBoCq/uei1M/wws=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.50.211.159:51820

PersistentKeepalive = 25