[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = gCRaP/+rE4jf7OZS0eZEbcgfhT8EtnAyT2bKWRMDmXE=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#27
PublicKey = W0ke+9ooJLu/AnDM3pcbkn8e+PfjScXywBCsXdlEmwE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.22.88.58:51820

PersistentKeepalive = 25